server.port=9291

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/property_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vikasks2004kannangi2@gmail.com
spring.mail.password=wquv mses sjiv cfei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Custom Application Configs
jwt.secret=vikas-solo-secret-key-that-is-at-least-256-bits-long-to-be-secure
aws.s3.bucket=project-rentalmarketplace
aws.s3.url=https://project-rentalmarketplace.s3.ap-south-1.amazonaws.com/
